{% set name = "txl-local-kernels" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_local_kernels-{{ version }}.tar.gz
  sha256: 74f0c71822b7767186ac372bd8aeb4c8b81bd5d2294e138b74b4335a170eb2cd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - txl-kernel
    - pyzmq >=24.0.1
    - ipykernel

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_local_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  summary: TXL plugin for local kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/local_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
